Changes to support MacOS
ChuckPa/PlexDBRepair pull request #9
Opened 2022-11-15 02:22 UTC by 2bits

Fixes: #2 

This includes all the changes needed to make PlexDBRepair work on MacOS.
Take a look at the code, and let me know your thoughts.

Unresolved:
- On a Mac there's no `plexmediaserver.pid` so I decided to create one during `HostConfig()` - wrong place to do so?
- The logic to check whether PMS is running can be defeated on a Mac as written in this PR at this time, by starting PMS after DBRepair is running (because I would not have made a `pid` file in `HostConfig`). So that should be sorted out.
- a bit of spacing and cleanup

Ok then, G'day.

2022-11-15 02:47 UTC, ChuckPa requested changes
1. plexmediaserver.pid

Suggest putting plexmediaserver.pid in /tmp so it doesn't persist and we make a mess.
The purpose of looking for it is PMS detection which isn't 100% reliable.   

When PMS crashes,  the PID file remains.   It's up to the packaging to determine if PMS is really running/
For that reason,  looking for the actual pid  (pidof) is the better test.

2.  Defeating PMS start.

It's known PMS can be started while this is running.
There are times when you might want to 
- Effect some change while in the tool 
- Start PMS to observe the impact
- UNDO the action if PMS adversely impacted.

By keeping the tool open,  the temp files are all still sitting there and easily accessible for UNDO.

Otherwise looks good.
You've tested this on Mac?

I'll need to test the branch on QNAP and Syno when ready.

2022-11-15 03:52 UTC, 2bits commented
1. Ok I'll move `plexmediaserver.pid` to `TMPDIR` but I'm not sure it's working which leads to (2).
2. Yes sir I understand it's a supported feature to start PMS while DBRepair is running. I read that in your docs and was trying to test it on the Mac. I got stuck though.  I should sleep on a few things I don't understand, such as:

- Why do you check both of these? Life would be easier if you tested only `pidof` but I admit I don't get it.
- `if [ -f "$PID_FILE" ] && [ "$($PIDOF 'Plex Media Server')" != "" ] ; then`

Let me know what you think while I do some logic experiments on this.

Case 1:
- user reindexes on a non-Mac host.
- leaves DBRepair running at the menu.
- Starts PMS and tests. Doesn't like it. Leaves PMS running.
- Chooses Undo in DBRepair. It moves back the previous db while PMS is running.
-  When it gets back to just before the main menu, it tests if PMS is running, sees it is, and does a hard abort, `exit 1`


Case 2:
- user reindexes on a non-Mac host
- leaves DBRepair running at the menu.
- Starts PMS and tests. Doesn't like it. Quits PMS.
- Chooses Undo in DBRepair. It moves back the previous db.
-  Returns to the Main Menu


Case 3:
- User Reindexes on a Mac, but the code only generates a PID file, the way I wrote it now, during HostConfig(). If we really want an up to date `pid` file, then I'll have to create it just before each Main Menu cycle.  I'll have to use PIDOF to check if PMS is running then create a `pid` file  just before you use PIDOF and the PID file to check if PMS is running. Yikes. :smile:

2022-11-15 04:42 UTC, ChuckPa commented
1. plexmediaserver.pid

Putting it in /tmp keeps this code working without interfering with whatever the Engineering team does for MacOS  (it  get's special treatment  because it's MacOS)

Some of the platforms work well with `plexmediaserver.pid` and some don't.   I test for it on the off chance we're running on a host where it's reliable.

2.  Interterlock with running PMS.

Does it make sense to actually test for PMS running at the top of  (inside) the menu loop ?
If so,  then we have a whole new situation to resolve which will need code to handle it.

Situation being:    PMS is running -  Wait forever for it to stop  or  only allow the exit command to do anything?

2022-11-15 05:34 UTC, 2bits commented
To answer your question of whether DBRepair should check for PMS running, I need to ask,
what are the negative impacts of a utility like `DBRepair.sh` changing a db that's in use?

Whatever you decide, you can always 
1. Check for PMS running at startup and exit cleanly if it is.
2. If the script gets past that, then the Main Menu loop starts with the menu.
3. The user makes a choice.
4. We test the choice like this `if [ ( ChoiceIsDangerous && ItsRunning ) ]; then; echo "can't do $choice" && break`
5. else do it
6. loop back to main menu.

2022-11-15 05:42 UTC, ChuckPa commented
1.  I check for PMS running at start and exit if it is before even going any further.
2. The negative impacts of operating on the DB while PMS is running is a destroyed DB.
3.  I like your function name  and think about  

The test becomes simple and we go right back to the top of the menu.


```
   PlexIsRunning && continue
```
There's some more logic to work out to make this fully idiot proof

2022-11-15 09:53 UTC, 2bits commented
I added a couple of commits, and it works as intended on Mac 10.14.6 (x64) and 12.6.1 (arm64).
It's ready for testing on your end, and I'll test it on QNAP and Pi 4B in the morning.
Thanks.

2022-11-15 18:59 UTC, 2bits commented
Hello,

testing on QNAP-4.5.4 - success!
testing on Pi 4B - looking into it

2022-11-16 06:02 UTC, ChuckPa approved these changes

2022-11-16 06:02 UTC, merged

2022-11-16 06:20 UTC, ChuckPa commented
v0.5.0 is released